apiVersion: v1
kind: Namespace
metadata:
  name: server-homepage
---
apiVersion: v1
kind: Service
metadata:
  name: server-homepage
  namespace: server-homepage
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: server-homepage
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-homepage
  namespace: server-homepage
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: server-homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: server-homepage
    spec:
      containers:
        - env:
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/name']
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: k8s.pod.uid=$(POD_UID),k8s.cluster.name=ihwa,k8s.container.name=server-homepage
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://ingest.otelcol.svc:4317
          image: ko://go.seankhliao.com/mono/cmd/server-homepage
          name: server-homepage
          ports:
            - containerPort: 8080
              name: http
      enableServiceLinks: false
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: server-homepage
  namespace: server-homepage
spec:
  hostnames:
    - justia.liao.dev
  parentRefs:
    - name: http-gateway
      namespace: envoy-gateway-system
  rules:
    - backendRefs:
        - name: server-homepage
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
