apiVersion: v1
kind: Namespace
metadata:
  name: testclickhouse
---
apiVersion: v1
kind: Service
metadata:
  name: testclickhouse
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: testclickhouse
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testclickhouse
  namespace: testclickhouse
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: testclickhouse
  template:
    metadata:
      labels:
        app.kubernetes.io/name: testclickhouse
    spec:
      containers:
        - env:
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/name']
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: k8s.pod.uid=$(POD_UID),k8s.cluster.name=ihwa,k8s.container.name=testclickhouse
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://ingest.otelcol.svc:4317
          image: ghcr.io/seankhliao/testclickhouse
          name: testclickhouse
          ports:
            - containerPort: 8080
              name: http
      enableServiceLinks: false
