apiVersion: v1
kind: Namespace
metadata:
  name: earbug
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: earbug
  namespace: earbug
spec:
  hostnames:
    - earbug.liao.dev
  parentRefs:
    - name: http-gateway
      namespace: envoy-gateway-system
  rules:
    - backendRefs:
        - name: earbug
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
---
apiVersion: v1
kind: Service
metadata:
  name: earbug
  namespace: earbug
spec:
  ports:
    - appProtocol: http
      name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: earbug
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: earbug
  namespace: earbug
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: earbug
  serviceName: earbug
  template:
    metadata:
      labels:
        app.kubernetes.io/name: earbug
    spec:
      containers:
        - env:
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/name']
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: k8s.pod.uid=$(POD_UID),k8s.cluster.name=justia,k8s.container.name=earbug
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otelcol.opentelemetry.svc:4317
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/workload-identity/creds.json
          image: ko://go.seankhliao.com/mono/cmd/earbug
          name: earbug
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - mountPath: /data
              name: data
            - name: token
              mountPath: /var/run/service-account
              readOnly: true
            - name: gcp-creds
              mountPath: /etc/workload-identity
              readOnly: true
      enableServiceLinks: false
      serviceAccountName: earbug
      volumes:
        - name: token
          projected:
            sources:
              - serviceAccountToken:
                  audience: https://iam.googleapis.com/projects/330311169810/locations/global/workloadIdentityPools/kubernetes/providers/justia-asami
                  expirationSeconds: 3600
                  path: token
        - name: gcp-creds
          configMap:
            name: gcp
        - name: data
          hostPath:
            path: /opt/volumes/earbug
  # volumeClaimTemplates:
  #   - apiVersion: v1
  #     kind: PersistentVolumeClaim
  #     metadata:
  #       labels:
  #         app.kubernetes.io/name: earbug
  #         app.kubernetes.io/version: v0.0.1
  #       name: data
  #     spec:
  #       accessModes:
  #         - ReadWriteOnce
  #       resources:
  #         requests:
  #           storage: 1Gi
  #       storageClassName: local-path
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: earbug
  namespace: earbug
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gcp
  namespace: earbug
data:
  creds.json: |
    {
      "universe_domain": "googleapis.com",
      "type": "external_account",
      "audience": "//iam.googleapis.com/projects/330311169810/locations/global/workloadIdentityPools/kubernetes/providers/justia-asami",
      "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
      "token_url": "https://sts.googleapis.com/v1/token",
      "credential_source": {
        "file": "/var/run/service-account/token",
        "format": {
          "type": "text"
        }
      },
      "token_info_url": "https://sts.googleapis.com/v1/introspect"
    }
