# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.31.1-standalone/namespace-v1.json
apiVersion: v1
kind: Namespace
metadata:
  name: goproxyaudit
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    app.kubernetes.io/name: goproxyaudit
  name: goproxyaudit
  namespace: goproxyaudit
spec:
  hostnames:
  - goproxyaudit.liao.dev
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: http-gateway
    namespace: envoy-gateway-system
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: goproxyaudit
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.31.1-standalone/service-v1.json
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: goproxyaudit
  name: goproxyaudit
  namespace: goproxyaudit
spec:
  ports:
  - appProtocol: http
    name: http
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: http
    name: debug
    port: 8082
    protocol: TCP
    targetPort: debug
  selector:
    app.kubernetes.io/name: goproxyaudit
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.31.1-standalone/deployment-apps-v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goproxyaudit
  namespace: goproxyaudit
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: goproxyaudit
  template:
    metadata:
      labels:
        app.kubernetes.io/name: goproxyaudit
    spec:
      containers:
        - env:
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/name']
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: k8s.container.name=goproxyaudit,service.instance.id=$(POD_UID),k8s.namespace.name=$(POD_NAMESPACE),k8s.pod.name=$(POD_NAME),k8s.pod.uid=$(POD_UID),k8s.node.name=$(NODE_NAME)
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otelcol.opentelemetry.svc:4317
            - name: LOG_LEVEL
              value: debug
          image: registry.liao.dev/goproxyaudit
          name: goproxyaudit
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8082
              name: debug
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 6
              memory: 8Gi
          volumeMounts:
            - name: data
              mountPath: /data
      enableServiceLinks: false
      serviceAccountName: goproxyaudit
      volumes:
        - name: data
          hostPath:
            path: /opt/volumes/goproxyaudit
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.31.1-standalone/serviceaccount-v1.json
apiVersion: v1
kind: ServiceAccount
metadata:
  name: goproxyaudit
  namespace: goproxyaudit
