apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/description: |
      Sets default settings for github repos
    run.googleapis.com/client-name: skaffold
    run.googleapis.com/ingress: all
    run.googleapis.com/launch-stage: BETA
  labels:
    cloud.googleapis.com/location: us-central1
  name: ghdefaults-seankhliao-com
  namespace: "330311169810"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
        run.googleapis.com/cpu-throttling: 'true'
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 1000
      containers:
        - image: us-central1-docker.pkg.dev/com-seankhliao/run/ghdefaults
          env:
            - name: LOG_FORMAT
              value: json
            - name: OTEL_LOGS_EXPORTER
              value: none
            - name: OTEL_METRICS_EXPORTER
              value: none
            - name: OTEL_TRACES_EXPORTER
              value: none
            - name: GITHUB_APP_ID
              value: '126001'
            - name: GITHUB_APP_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  key: 1
                  name: ghdefaults-github-app-private-key
            - name: GITHUB_APP_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  key: 1
                  name: ghdefaults-github-app-webhook-secret

          ports:
            - containerPort: 8080
              name: h2c
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
      serviceAccountName: ghdefaults-seankhliao-com@com-seankhliao.iam.gserviceaccount.com
      timeoutSeconds: 15
  traffic:
    - latestRevision: true
      percent: 100
