apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/client-name: skaffold
    run.googleapis.com/default-url-disabled: "true"
    run.googleapis.com/invoker-iam-disabled: 'true'
    run.googleapis.com/description: |
      Sets default settings for github repos
    run.googleapis.com/ingress: all
    run.googleapis.com/launch-stage: BETA
  labels:
    cloud.googleapis.com/location: us-central1
  name: ghdefaults-seankhliao-com
  namespace: "330311169810"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: "false"
    spec:
      containerConcurrency: 1000
      containers:
        - image: us-central1-docker.pkg.dev/com-seankhliao/run/ghdefaults
          env:
            - name: LOG_FORMAT
              value: json
            - name: OTEL_LOGS_EXPORTER
              value: none
            - name: OTEL_METRICS_EXPORTER
              value: none
            - name: OTEL_TRACES_EXPORTER
              value: none
            - name: GITHUB_APP_ID
              value: "126001"
            - name: CONFIG_FILE
              value: /config/config.json
          ports:
            - containerPort: 8080
              name: h2c
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          volumeMounts:
            - name: gcs-1
              mountPath: /config
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 8080
      serviceAccountName: ghdefaults-seankhliao-com@com-seankhliao.iam.gserviceaccount.com
      timeoutSeconds: 15
      volumes:
        - name: gcs-1
          csi:
            driver: gcsfuse.run.googleapis.com
            readOnly: true
            volumeAttributes:
              bucketName: ghdefaults-seankhliao-com
  traffic:
    - latestRevision: true
      percent: 100
