apiVersion: v1
kind: Namespace
metadata:
  name: youtubefeed
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: youtubefeed
spec:
  hostnames:
    - youtubefeed.ihwa.liao.dev
  parentRefs:
    - name: default
      namespace: envoy-gateway-system
  rules:
    - backendRefs:
        - name: youtubefeed
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
---
apiVersion: v1
kind: Service
metadata:
  name: youtubefeed
  namespace: youtubefeed
spec:
  ports:
    - appProtocol: HTTP
      name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: youtubefeed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtubefeed
  namespace: youtubefeed
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: youtubefeed
  template:
    metadata:
      labels:
        app.kubernetes.io/name: youtubefeed
    spec:
      containers:
        - args:
            - -mode=serve
          envFrom:
            - secretRef:
                name: youtubefeed
          env:
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/name']
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: k8s.pod.uid=$(POD_UID),k8s.cluster.name=ihwa,k8s.container.name=youtubefeed
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://ingest.otelcol.svc:4317
          image: ghcr.io/seankhliao/youtubefeed
          name: youtubefeed
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
      enableServiceLinks: false
