# crane digest gcr.io/distroless/static-debian12:nonroot
# sha256:3a03fc0826340c7deb82d4755ca391bef5adcedb8892e58412e1a6008199fa91
defaultBaseImage: gcr.io/distroless/static-debian12:nonroot@sha256:3a03fc0826340c7deb82d4755ca391bef5adcedb8892e58412e1a6008199fa91
defaultPlatforms:
  - linux/arm64
  - linux/amd64

_buildopts: &buildopts
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s
    - -w

builds:
  - id: fin
    main: ./cmd/fin
    <<: *buildopts
  - id: moo
    main: ./cmd/moo
    <<: *buildopts
  - id: ytfeed
    main: ./cmd/ytfeed
    <<: *buildopts
