defaultBaseImage: gcr.io/distroless/static-debian12:nonroot@sha256:67686c9070e7179449c73943d89160c4834c0b4a969434022e11c5b9a8dc6131
defaultPlatforms:
  - linux/arm64
  - linux/amd64

_buildopts: &buildopts
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s
    - -w

builds:
  - id: authsvr
    main: ./cmd/authsvr
    <<: *buildopts
  - id: earbug
    main: ./cmd/earbug
    <<: *buildopts
  - id: fin
    main: ./cmd/fin
    <<: *buildopts
  - id: ghdefaults
    main: ./cmd/ghdefaults
    <<: *buildopts
  - id: moo
    main: ./cmd/moo
    <<: *buildopts
  - id: reqlog
    main: ./cmd/reqlog
    <<: *buildopts
  - id: server-homepage
    main: ./cmd/server-homepage
    <<: *buildopts
  - id: ytfeed
    main: ./cmd/ytfeed
    <<: *buildopts
