apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: authsvr
build:
  artifacts:
    - image: ghcr.io/seankhliao/authsvr
      ko:
        main: ./cmd/authsvr
        env:
          - CGO_ENABLED=0
        ldflags:
          - -s
          - -w
        dependencies:
          paths:
            - go.mod
            # go list -deps -f '{{if .Module}}{{if .Module.Main}}{{.Dir}}{{end}}{{end}}' ./cmd/authsvr | xargs realpath --relative-to .
            - jsonlog
            - observability
            - basehttp
            - framework
            - webstyle/picture
            - webstyle
            - httpencoding
            - webstyle/webstatic
            - cmd/authsvr
  tagPolicy:
    inputDigest: {}
  platforms:
    - linux/amd64
    - linux/arm64
manifests:
  rawYaml:
    - cmd/authsvr/kubernetes.yaml
deploy:
  kubeContext: ihwa
  kubectl:
    defaultNamespace: authsvr
---
apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: earbug
build:
  artifacts:
    - image: ghcr.io/seankhliao/earbug
      ko:
        main: ./cmd/earbug
        env:
          - CGO_ENABLED=0
        ldflags:
          - -s
          - -w
        dependencies:
          paths:
            - go.mod
            # go list -deps -f '{{if .Module}}{{if .Module.Main}}{{.Dir}}{{end}}{{end}}' ./cmd/authsvr | xargs realpath --relative-to .
            - jsonlog
            - observability
            - authed
            - cmd/earbug/earbugv4
            - basehttp
            - framework
            - httpencoding
            - webstyle/picture
            - webstyle
            - webstyle/webstatic
            - cmd/earbug
  tagPolicy:
    inputDigest: {}
  platforms:
    - linux/amd64
    - linux/arm64
manifests:
  rawYaml:
    - cmd/earbug/kubernetes.yaml
    - cmd/earbug/secrets.sopssecret.yaml
deploy:
  kubeContext: ihwa
  kubectl:
    defaultNamespace: earbug
---
apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: fin
build:
  artifacts:
    - image: ghcr.io/seankhliao/fin
      ko:
        main: ./cmd/fin
        env:
          - CGO_ENABLED=0
        flags:
          - -trimpath
        ldflags:
          - -s
          - -w
        dependencies:
          paths:
            - go.mod
            # go list -deps -f '{{if .Module}}{{if .Module.Main}}{{.Dir}}{{end}}{{end}}' ./cmd/fin | xargs realpath --relative-to .
            - jsonlog
            - observability
            - authed
            - cmd/fin/findata
            - basehttp
            - framework
            - httpencoding
            - webstyle/picture
            - webstyle
            - webstyle/webstatic
            - cmd/fin
  tagPolicy:
    inputDigest: {}
  platforms:
    - linux/amd64
    - linux/arm64
manifests:
  rawYaml:
    - cmd/fin/kubernetes.yaml
deploy:
  kubeContext: ihwa
  kubectl:
    defaultNamespace: fin
---
apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: ghdefaults
build:
  artifacts:
    - image: ghcr.io/seankhliao/ghdefaults
      ko:
        main: ./cmd/ghdefaults
        env:
          - CGO_ENABLED=0
        flags:
          - -trimpath
        ldflags:
          - -s
          - -w
        dependencies:
          paths:
            - go.mod
            # go list -deps -f '{{if .Module}}{{if .Module.Main}}{{.Dir}}{{end}}{{end}}' ./cmd/ghdefaults | xargs realpath --relative-to .
            - jsonlog
            - observability
            - basehttp
            - framework
            - cmd/ghdefaults
  tagPolicy:
    inputDigest: {}
  platforms:
    - linux/amd64
    - linux/arm64
manifests:
  rawYaml:
    - cmd/ghdefaults/kubernetes.yaml
    - cmd/ghdefaults/secrets.sopssecret.yaml
deploy:
  kubeContext: ihwa
  kubectl:
    defaultNamespace: ghdefaults
---
apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: ihwa-liao-dev
build:
  artifacts:
    - image: ghcr.io/seankhliao/ihwa-liao-dev
      ko:
        main: ./cmd/ihwa.liao.dev
        env:
          - CGO_ENABLED=0
        flags:
          - -trimpath
        ldflags:
          - -s
          - -w
        dependencies:
          paths:
            - go.mod
            # go list -deps -f '{{if .Module}}{{if .Module.Main}}{{.Dir}}{{end}}{{end}}' ./cmd/ihwa.liao.dev | xargs realpath --relative-to .
            - jsonlog
            - observability
            - basehttp
            - framework
            - httpencoding
            - webstyle/picture
            - webstyle
            - webstyle/webstatic
            - cmd/ihwa.liao.dev
  tagPolicy:
    inputDigest: {}
  platforms:
    - linux/amd64
    - linux/arm64
manifests:
  rawYaml:
    - cmd/ihwa.liao.dev/kubernetes.yaml
deploy:
  kubeContext: ihwa
  kubectl:
    defaultNamespace: ihwa-liao-dev
---
apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: vanity
build:
  artifacts:
    - image: us-central1-docker.pkg.dev/com-seankhliao/run/vanity
      ko:
        main: ./cmd/vanity
        env:
          - CGO_ENABLED=0
        flags:
          - -trimpath
        ldflags:
          - -s
          - -w
        dependencies:
          paths:
            - go.mod
            # go list -deps -f '{{if .Module}}{{if .Module.Main}}{{.Dir}}{{end}}{{end}}' ./cmd/vanity | xargs realpath --relative-to .
            - jsonlog
            - observability
            - basehttp
            - framework
            - webstyle/picture
            - webstyle
            - httpencoding
            - webstyle/webstatic
            - cmd/vanity
  tagPolicy:
    inputDigest: {}
  platforms:
    - linux/amd64
manifests:
  rawYaml:
    - cmd/vanity/cloudrun.yaml
deploy:
  cloudrun:
    region: us-central1
---
apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: youtubefeed
build:
  artifacts:
    - image: ghcr.io/seankhliao/youtubefeed
      ko:
        main: ./cmd/youtubefeed
        env:
          - CGO_ENABLED=0
        flags:
          - -trimpath
        ldflags:
          - -s
          - -w
        dependencies:
          paths:
            - go.mod
            # go list -deps -f '{{if .Module}}{{if .Module.Main}}{{.Dir}}{{end}}{{end}}' ./cmd/youtubefeed | xargs realpath --relative-to .
            - jsonlog
            - observability
            - authed
            - basehttp
            - framework
            - httpencoding
            - webstyle/picture
            - webstyle
            - webstyle/webstatic
            - cmd/youtubefeed
  tagPolicy:
    inputDigest: {}
  platforms:
    - linux/amd64
    - linux/arm64
manifests:
  rawYaml:
    - cmd/youtubefeed/kubernetes.yaml
    - cmd/youtubefeed/secrets.sopssecret.yaml
deploy:
  kubeContext: ihwa
  kubectl:
    defaultNamespace: youtubefeed
