apiVersion: v1
kind: Namespace
metadata:
  name: ytfeed
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: ytfeed
  namespace: ytfeed
spec:
  hostnames:
    - ytfeed.ihwa.liao.dev
  parentRefs:
    - name: default
      namespace: envoy-gateway-system
  rules:
    - backendRefs:
        - name: ytfeed
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
---
apiVersion: v1
kind: Service
metadata:
  name: ytfeed
  namespace: ytfeed
spec:
  ports:
    - appProtocol: HTTP
      name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: ytfeed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ytfeed
  namespace: ytfeed
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ytfeed
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ytfeed
    spec:
      containers:
        - args:
            - -mode=serve
          envFrom:
            - secretRef:
                name: ytfeed
          env:
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/name']
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: k8s.pod.uid=$(POD_UID),k8s.cluster.name=ihwa,k8s.container.name=ytfeed
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://ingest.otelcol.svc:4317
          image: ko://go.seankhliao.com/mono/cmd/ytfeed
          name: ytfeed
          ports:
            - containerPort: 8080
              name: http
      enableServiceLinks: false
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: ytfeed
  namespace: ytfeed
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ytfeed
