// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        (unknown)
// source: goproxyaudit/v1/store.proto

package goproxyauditv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Store struct {
	state                         protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_Root               map[string]*ModuleSegment `protobuf:"bytes,1,rep,name=root" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_GolangOrgLastIndex *timestamppb.Timestamp    `protobuf:"bytes,10,opt,name=golang_org_last_index,json=golangOrgLastIndex"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *Store) Reset() {
	*x = Store{}
	mi := &file_goproxyaudit_v1_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Store) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Store) ProtoMessage() {}

func (x *Store) ProtoReflect() protoreflect.Message {
	mi := &file_goproxyaudit_v1_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Store) GetRoot() map[string]*ModuleSegment {
	if x != nil {
		return x.xxx_hidden_Root
	}
	return nil
}

func (x *Store) GetGolangOrgLastIndex() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_GolangOrgLastIndex
	}
	return nil
}

func (x *Store) SetRoot(v map[string]*ModuleSegment) {
	x.xxx_hidden_Root = v
}

func (x *Store) SetGolangOrgLastIndex(v *timestamppb.Timestamp) {
	x.xxx_hidden_GolangOrgLastIndex = v
}

func (x *Store) HasGolangOrgLastIndex() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_GolangOrgLastIndex != nil
}

func (x *Store) ClearGolangOrgLastIndex() {
	x.xxx_hidden_GolangOrgLastIndex = nil
}

type Store_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Root               map[string]*ModuleSegment
	GolangOrgLastIndex *timestamppb.Timestamp
}

func (b0 Store_builder) Build() *Store {
	m0 := &Store{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Root = b.Root
	x.xxx_hidden_GolangOrgLastIndex = b.GolangOrgLastIndex
	return m0
}

type ModuleSegment struct {
	state               protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_Module   *Module                   `protobuf:"bytes,1,opt,name=module"`
	xxx_hidden_Children map[string]*ModuleSegment `protobuf:"bytes,2,rep,name=children" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ModuleSegment) Reset() {
	*x = ModuleSegment{}
	mi := &file_goproxyaudit_v1_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleSegment) ProtoMessage() {}

func (x *ModuleSegment) ProtoReflect() protoreflect.Message {
	mi := &file_goproxyaudit_v1_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ModuleSegment) GetModule() *Module {
	if x != nil {
		return x.xxx_hidden_Module
	}
	return nil
}

func (x *ModuleSegment) GetChildren() map[string]*ModuleSegment {
	if x != nil {
		return x.xxx_hidden_Children
	}
	return nil
}

func (x *ModuleSegment) SetModule(v *Module) {
	x.xxx_hidden_Module = v
}

func (x *ModuleSegment) SetChildren(v map[string]*ModuleSegment) {
	x.xxx_hidden_Children = v
}

func (x *ModuleSegment) HasModule() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Module != nil
}

func (x *ModuleSegment) ClearModule() {
	x.xxx_hidden_Module = nil
}

type ModuleSegment_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Module   *Module
	Children map[string]*ModuleSegment
}

func (b0 ModuleSegment_builder) Build() *ModuleSegment {
	m0 := &ModuleSegment{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Module = b.Module
	x.xxx_hidden_Children = b.Children
	return m0
}

type Module struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ModuleName  *string                `protobuf:"bytes,1,opt,name=module_name,json=moduleName"`
	xxx_hidden_Latest      *string                `protobuf:"bytes,2,opt,name=latest"`
	xxx_hidden_Versions    *[]*ModuleVersion      `protobuf:"bytes,3,rep,name=versions"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Module) Reset() {
	*x = Module{}
	mi := &file_goproxyaudit_v1_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Module) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Module) ProtoMessage() {}

func (x *Module) ProtoReflect() protoreflect.Message {
	mi := &file_goproxyaudit_v1_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Module) GetModuleName() string {
	if x != nil {
		if x.xxx_hidden_ModuleName != nil {
			return *x.xxx_hidden_ModuleName
		}
		return ""
	}
	return ""
}

func (x *Module) GetLatest() string {
	if x != nil {
		if x.xxx_hidden_Latest != nil {
			return *x.xxx_hidden_Latest
		}
		return ""
	}
	return ""
}

func (x *Module) GetVersions() []*ModuleVersion {
	if x != nil {
		if x.xxx_hidden_Versions != nil {
			return *x.xxx_hidden_Versions
		}
	}
	return nil
}

func (x *Module) SetModuleName(v string) {
	x.xxx_hidden_ModuleName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *Module) SetLatest(v string) {
	x.xxx_hidden_Latest = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *Module) SetVersions(v []*ModuleVersion) {
	x.xxx_hidden_Versions = &v
}

func (x *Module) HasModuleName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Module) HasLatest() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Module) ClearModuleName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ModuleName = nil
}

func (x *Module) ClearLatest() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Latest = nil
}

type Module_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ModuleName *string
	Latest     *string
	Versions   []*ModuleVersion
}

func (b0 Module_builder) Build() *Module {
	m0 := &Module{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ModuleName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_ModuleName = b.ModuleName
	}
	if b.Latest != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Latest = b.Latest
	}
	x.xxx_hidden_Versions = &b.Versions
	return m0
}

type ModuleVersion struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Version          *string                `protobuf:"bytes,1,opt,name=version"`
	xxx_hidden_GolangOrgIndexed *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=golang_org_indexed,json=golangOrgIndexed"`
	xxx_hidden_GolangOrgCached  bool                   `protobuf:"varint,11,opt,name=golang_org_cached,json=golangOrgCached"`
	xxx_hidden_GolangOrgError   *string                `protobuf:"bytes,13,opt,name=golang_org_error,json=golangOrgError"`
	xxx_hidden_GolangOrgSum     []byte                 `protobuf:"bytes,14,opt,name=golang_org_sum,json=golangOrgSum"`
	xxx_hidden_GolangOrgCommit  *string                `protobuf:"bytes,15,opt,name=golang_org_commit,json=golangOrgCommit"`
	xxx_hidden_DirectChecked    *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=direct_checked,json=directChecked"`
	xxx_hidden_DirectHost       *string                `protobuf:"bytes,21,opt,name=direct_host,json=directHost"`
	xxx_hidden_DirectVcs        *string                `protobuf:"bytes,22,opt,name=direct_vcs,json=directVcs"`
	xxx_hidden_DirectError      *string                `protobuf:"bytes,23,opt,name=direct_error,json=directError"`
	xxx_hidden_DirectSum        *string                `protobuf:"bytes,24,opt,name=direct_sum,json=directSum"`
	xxx_hidden_DirectCommit     *string                `protobuf:"bytes,25,opt,name=direct_commit,json=directCommit"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ModuleVersion) Reset() {
	*x = ModuleVersion{}
	mi := &file_goproxyaudit_v1_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleVersion) ProtoMessage() {}

func (x *ModuleVersion) ProtoReflect() protoreflect.Message {
	mi := &file_goproxyaudit_v1_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ModuleVersion) GetVersion() string {
	if x != nil {
		if x.xxx_hidden_Version != nil {
			return *x.xxx_hidden_Version
		}
		return ""
	}
	return ""
}

func (x *ModuleVersion) GetGolangOrgIndexed() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_GolangOrgIndexed
	}
	return nil
}

func (x *ModuleVersion) GetGolangOrgCached() bool {
	if x != nil {
		return x.xxx_hidden_GolangOrgCached
	}
	return false
}

func (x *ModuleVersion) GetGolangOrgError() string {
	if x != nil {
		if x.xxx_hidden_GolangOrgError != nil {
			return *x.xxx_hidden_GolangOrgError
		}
		return ""
	}
	return ""
}

func (x *ModuleVersion) GetGolangOrgSum() []byte {
	if x != nil {
		return x.xxx_hidden_GolangOrgSum
	}
	return nil
}

func (x *ModuleVersion) GetGolangOrgCommit() string {
	if x != nil {
		if x.xxx_hidden_GolangOrgCommit != nil {
			return *x.xxx_hidden_GolangOrgCommit
		}
		return ""
	}
	return ""
}

func (x *ModuleVersion) GetDirectChecked() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DirectChecked
	}
	return nil
}

func (x *ModuleVersion) GetDirectHost() string {
	if x != nil {
		if x.xxx_hidden_DirectHost != nil {
			return *x.xxx_hidden_DirectHost
		}
		return ""
	}
	return ""
}

func (x *ModuleVersion) GetDirectVcs() string {
	if x != nil {
		if x.xxx_hidden_DirectVcs != nil {
			return *x.xxx_hidden_DirectVcs
		}
		return ""
	}
	return ""
}

func (x *ModuleVersion) GetDirectError() string {
	if x != nil {
		if x.xxx_hidden_DirectError != nil {
			return *x.xxx_hidden_DirectError
		}
		return ""
	}
	return ""
}

func (x *ModuleVersion) GetDirectSum() string {
	if x != nil {
		if x.xxx_hidden_DirectSum != nil {
			return *x.xxx_hidden_DirectSum
		}
		return ""
	}
	return ""
}

func (x *ModuleVersion) GetDirectCommit() string {
	if x != nil {
		if x.xxx_hidden_DirectCommit != nil {
			return *x.xxx_hidden_DirectCommit
		}
		return ""
	}
	return ""
}

func (x *ModuleVersion) SetVersion(v string) {
	x.xxx_hidden_Version = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 12)
}

func (x *ModuleVersion) SetGolangOrgIndexed(v *timestamppb.Timestamp) {
	x.xxx_hidden_GolangOrgIndexed = v
}

func (x *ModuleVersion) SetGolangOrgCached(v bool) {
	x.xxx_hidden_GolangOrgCached = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 12)
}

func (x *ModuleVersion) SetGolangOrgError(v string) {
	x.xxx_hidden_GolangOrgError = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 12)
}

func (x *ModuleVersion) SetGolangOrgSum(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_GolangOrgSum = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 12)
}

func (x *ModuleVersion) SetGolangOrgCommit(v string) {
	x.xxx_hidden_GolangOrgCommit = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 12)
}

func (x *ModuleVersion) SetDirectChecked(v *timestamppb.Timestamp) {
	x.xxx_hidden_DirectChecked = v
}

func (x *ModuleVersion) SetDirectHost(v string) {
	x.xxx_hidden_DirectHost = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 12)
}

func (x *ModuleVersion) SetDirectVcs(v string) {
	x.xxx_hidden_DirectVcs = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 12)
}

func (x *ModuleVersion) SetDirectError(v string) {
	x.xxx_hidden_DirectError = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 12)
}

func (x *ModuleVersion) SetDirectSum(v string) {
	x.xxx_hidden_DirectSum = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 12)
}

func (x *ModuleVersion) SetDirectCommit(v string) {
	x.xxx_hidden_DirectCommit = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 11, 12)
}

func (x *ModuleVersion) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ModuleVersion) HasGolangOrgIndexed() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_GolangOrgIndexed != nil
}

func (x *ModuleVersion) HasGolangOrgCached() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ModuleVersion) HasGolangOrgError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ModuleVersion) HasGolangOrgSum() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ModuleVersion) HasGolangOrgCommit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *ModuleVersion) HasDirectChecked() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DirectChecked != nil
}

func (x *ModuleVersion) HasDirectHost() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *ModuleVersion) HasDirectVcs() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *ModuleVersion) HasDirectError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *ModuleVersion) HasDirectSum() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *ModuleVersion) HasDirectCommit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 11)
}

func (x *ModuleVersion) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Version = nil
}

func (x *ModuleVersion) ClearGolangOrgIndexed() {
	x.xxx_hidden_GolangOrgIndexed = nil
}

func (x *ModuleVersion) ClearGolangOrgCached() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_GolangOrgCached = false
}

func (x *ModuleVersion) ClearGolangOrgError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_GolangOrgError = nil
}

func (x *ModuleVersion) ClearGolangOrgSum() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_GolangOrgSum = nil
}

func (x *ModuleVersion) ClearGolangOrgCommit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_GolangOrgCommit = nil
}

func (x *ModuleVersion) ClearDirectChecked() {
	x.xxx_hidden_DirectChecked = nil
}

func (x *ModuleVersion) ClearDirectHost() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_DirectHost = nil
}

func (x *ModuleVersion) ClearDirectVcs() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_DirectVcs = nil
}

func (x *ModuleVersion) ClearDirectError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_DirectError = nil
}

func (x *ModuleVersion) ClearDirectSum() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_DirectSum = nil
}

func (x *ModuleVersion) ClearDirectCommit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 11)
	x.xxx_hidden_DirectCommit = nil
}

type ModuleVersion_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Version          *string
	GolangOrgIndexed *timestamppb.Timestamp
	GolangOrgCached  *bool
	GolangOrgError   *string
	GolangOrgSum     []byte
	GolangOrgCommit  *string
	DirectChecked    *timestamppb.Timestamp
	DirectHost       *string
	DirectVcs        *string
	DirectError      *string
	DirectSum        *string
	DirectCommit     *string
}

func (b0 ModuleVersion_builder) Build() *ModuleVersion {
	m0 := &ModuleVersion{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 12)
		x.xxx_hidden_Version = b.Version
	}
	x.xxx_hidden_GolangOrgIndexed = b.GolangOrgIndexed
	if b.GolangOrgCached != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 12)
		x.xxx_hidden_GolangOrgCached = *b.GolangOrgCached
	}
	if b.GolangOrgError != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 12)
		x.xxx_hidden_GolangOrgError = b.GolangOrgError
	}
	if b.GolangOrgSum != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 12)
		x.xxx_hidden_GolangOrgSum = b.GolangOrgSum
	}
	if b.GolangOrgCommit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 12)
		x.xxx_hidden_GolangOrgCommit = b.GolangOrgCommit
	}
	x.xxx_hidden_DirectChecked = b.DirectChecked
	if b.DirectHost != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 12)
		x.xxx_hidden_DirectHost = b.DirectHost
	}
	if b.DirectVcs != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 12)
		x.xxx_hidden_DirectVcs = b.DirectVcs
	}
	if b.DirectError != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 12)
		x.xxx_hidden_DirectError = b.DirectError
	}
	if b.DirectSum != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 12)
		x.xxx_hidden_DirectSum = b.DirectSum
	}
	if b.DirectCommit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 11, 12)
		x.xxx_hidden_DirectCommit = b.DirectCommit
	}
	return m0
}

var File_goproxyaudit_v1_store_proto protoreflect.FileDescriptor

var file_goproxyaudit_v1_store_proto_rawDesc = string([]byte{
	0x0a, 0x1b, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x61, 0x75, 0x64, 0x69, 0x74, 0x2f, 0x76,
	0x31, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x67,
	0x6f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x61, 0x75, 0x64, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xe5, 0x01, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x34, 0x0a, 0x04, 0x72, 0x6f, 0x6f,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x78,
	0x79, 0x61, 0x75, 0x64, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x2e,
	0x52, 0x6f, 0x6f, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x12,
	0x4d, 0x0a, 0x15, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x5f, 0x6f, 0x72, 0x67, 0x5f, 0x6c, 0x61,
	0x73, 0x74, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x12, 0x67, 0x6f, 0x6c, 0x61,
	0x6e, 0x67, 0x4f, 0x72, 0x67, 0x4c, 0x61, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x1a, 0x57,
	0x0a, 0x09, 0x52, 0x6f, 0x6f, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x34, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67,
	0x6f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x61, 0x75, 0x64, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xe7, 0x01, 0x0a, 0x0d, 0x4d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x2f, 0x0a, 0x06, 0x6d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x70, 0x72,
	0x6f, 0x78, 0x79, 0x61, 0x75, 0x64, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x52, 0x06, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x48, 0x0a, 0x08, 0x63, 0x68,
	0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x67,
	0x6f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x61, 0x75, 0x64, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x68, 0x69,
	0x6c, 0x64, 0x72, 0x65, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x63, 0x68, 0x69, 0x6c,
	0x64, 0x72, 0x65, 0x6e, 0x1a, 0x5b, 0x0a, 0x0d, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x34, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x78, 0x79,
	0x61, 0x75, 0x64, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x53,
	0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x7d, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x61,
	0x74, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x08, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x78, 0x79,
	0x61, 0x75, 0x64, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x22, 0x85, 0x04, 0x0a, 0x0d, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x48, 0x0a, 0x12,
	0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x5f, 0x6f, 0x72, 0x67, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x65, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x10, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x4f, 0x72, 0x67, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67,
	0x5f, 0x6f, 0x72, 0x67, 0x5f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x4f, 0x72, 0x67, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x5f, 0x6f, 0x72, 0x67,
	0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x67, 0x6f,
	0x6c, 0x61, 0x6e, 0x67, 0x4f, 0x72, 0x67, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x24, 0x0a, 0x0e,
	0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x5f, 0x6f, 0x72, 0x67, 0x5f, 0x73, 0x75, 0x6d, 0x18, 0x0e,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x4f, 0x72, 0x67, 0x53,
	0x75, 0x6d, 0x12, 0x2a, 0x0a, 0x11, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x5f, 0x6f, 0x72, 0x67,
	0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x67,
	0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x4f, 0x72, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12, 0x41,
	0x0a, 0x0e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64,
	0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x0d, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x65,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x68, 0x6f, 0x73, 0x74,
	0x18, 0x15, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x48, 0x6f,
	0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x76, 0x63, 0x73,
	0x18, 0x16, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x56, 0x63,
	0x73, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x17, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x73,
	0x75, 0x6d, 0x18, 0x18, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x53, 0x75, 0x6d, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x63, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x18, 0x19, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x42, 0xb5, 0x01, 0x0a, 0x13, 0x63, 0x6f, 0x6d,
	0x2e, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x61, 0x75, 0x64, 0x69, 0x74, 0x2e, 0x76, 0x31,
	0x42, 0x0a, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x35,
	0x67, 0x6f, 0x2e, 0x73, 0x65, 0x61, 0x6e, 0x6b, 0x68, 0x6c, 0x69, 0x61, 0x6f, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6d, 0x6f, 0x6e, 0x6f, 0x2f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x61, 0x75,
	0x64, 0x69, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x61, 0x75,
	0x64, 0x69, 0x74, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x47, 0x58, 0x58, 0xaa, 0x02, 0x0f, 0x47, 0x6f,
	0x70, 0x72, 0x6f, 0x78, 0x79, 0x61, 0x75, 0x64, 0x69, 0x74, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0f,
	0x47, 0x6f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x61, 0x75, 0x64, 0x69, 0x74, 0x5c, 0x56, 0x31, 0xe2,
	0x02, 0x1b, 0x47, 0x6f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x61, 0x75, 0x64, 0x69, 0x74, 0x5c, 0x56,
	0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x10,
	0x47, 0x6f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x61, 0x75, 0x64, 0x69, 0x74, 0x3a, 0x3a, 0x56, 0x31,
	0x62, 0x08, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x70, 0xe8, 0x07,
})

var file_goproxyaudit_v1_store_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_goproxyaudit_v1_store_proto_goTypes = []any{
	(*Store)(nil),                 // 0: goproxyaudit.v1.Store
	(*ModuleSegment)(nil),         // 1: goproxyaudit.v1.ModuleSegment
	(*Module)(nil),                // 2: goproxyaudit.v1.Module
	(*ModuleVersion)(nil),         // 3: goproxyaudit.v1.ModuleVersion
	nil,                           // 4: goproxyaudit.v1.Store.RootEntry
	nil,                           // 5: goproxyaudit.v1.ModuleSegment.ChildrenEntry
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_goproxyaudit_v1_store_proto_depIdxs = []int32{
	4, // 0: goproxyaudit.v1.Store.root:type_name -> goproxyaudit.v1.Store.RootEntry
	6, // 1: goproxyaudit.v1.Store.golang_org_last_index:type_name -> google.protobuf.Timestamp
	2, // 2: goproxyaudit.v1.ModuleSegment.module:type_name -> goproxyaudit.v1.Module
	5, // 3: goproxyaudit.v1.ModuleSegment.children:type_name -> goproxyaudit.v1.ModuleSegment.ChildrenEntry
	3, // 4: goproxyaudit.v1.Module.versions:type_name -> goproxyaudit.v1.ModuleVersion
	6, // 5: goproxyaudit.v1.ModuleVersion.golang_org_indexed:type_name -> google.protobuf.Timestamp
	6, // 6: goproxyaudit.v1.ModuleVersion.direct_checked:type_name -> google.protobuf.Timestamp
	1, // 7: goproxyaudit.v1.Store.RootEntry.value:type_name -> goproxyaudit.v1.ModuleSegment
	1, // 8: goproxyaudit.v1.ModuleSegment.ChildrenEntry.value:type_name -> goproxyaudit.v1.ModuleSegment
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_goproxyaudit_v1_store_proto_init() }
func file_goproxyaudit_v1_store_proto_init() {
	if File_goproxyaudit_v1_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goproxyaudit_v1_store_proto_rawDesc), len(file_goproxyaudit_v1_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_goproxyaudit_v1_store_proto_goTypes,
		DependencyIndexes: file_goproxyaudit_v1_store_proto_depIdxs,
		MessageInfos:      file_goproxyaudit_v1_store_proto_msgTypes,
	}.Build()
	File_goproxyaudit_v1_store_proto = out.File
	file_goproxyaudit_v1_store_proto_goTypes = nil
	file_goproxyaudit_v1_store_proto_depIdxs = nil
}
