apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/client-name: skaffold
    run.googleapis.com/default-url-disabled: "true"
    run.googleapis.com/ingress: all
    run.googleapis.com/invoker-iam-disabled: 'true'
    run.googleapis.com/launch-stage: BETA
    run.googleapis.com/maxScale: "1"
    run.googleapis.com/description: |
      Serves go custom import paths
  labels:
    cloud.googleapis.com/location: us-central1
  name: go-seankhliao-com
  namespace: "330311169810"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
        run.googleapis.com/cpu-throttling: 'true'
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 1000
      containers:
        - image: us-central1-docker.pkg.dev/com-seankhliao/run/vanity
          env:
            - name: LOG_FORMAT
              value: json
            - name: OTEL_LOGS_EXPORTER
              value: none
            - name: OTEL_METRICS_EXPORTER
              value: none
            - name: OTEL_TRACES_EXPORTER
              value: none
          ports:
            - containerPort: 8080
              name: h2c
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
      serviceAccountName: go-seankhliao-com@com-seankhliao.iam.gserviceaccount.com
      timeoutSeconds: 5
  traffic:
    - latestRevision: true
      percent: 100
