apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: vanity
build:
  artifacts:
    - image: us-central1-docker.pkg.dev/com-seankhliao/run/vanity
      ko:
        main: .
        fromImage: gcr.io/distroless/static-debian12:nonroot@sha256:3a03fc0826340c7deb82d4755ca391bef5adcedb8892e58412e1a6008199fa91
        env:
          - CGO_ENABLED=0
        flags:
          - -trimpath
        ldflags:
          - -s
          - -w
  tagPolicy:
    inputDigest: {}
  platforms:
    - linux/amd64
manifests:
  rawYaml:
    - cloudrun.yaml
deploy:
  cloudrun:
    region: us-central1
