apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: homepage
build:
  artifacts:
    - image: registry.liao.dev/homepage
      ko:
        main: .
        fromImage: gcr.io/distroless/static-debian12:nonroot@sha256:3a03fc0826340c7deb82d4755ca391bef5adcedb8892e58412e1a6008199fa91
        env:
          - CGO_ENABLED=0
        flags:
          - -trimpath
        ldflags:
          - -s
          - -w
  tagPolicy:
    inputDigest: {}
  platforms:
    - linux/amd64
    - linux/arm64/v8
manifests:
  rawYaml:
    - kubernetes.yaml
deploy:
  kubectl:
    defaultNamespace: homepage
  kubeContext: user@asami
