apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: reqlog
build:
  artifacts:
    - image: registry.liao.dev/reqlog
      ko:
        main: .
        fromImage: gcr.io/distroless/static-debian13:nonroot@sha256:fedcacdbe5eb1b1ec2ab5f2e7bf2eed246eb371505c43b3c2682ff0c3870e7c3
        env:
          - CGO_ENABLED=0
        flags:
          - -trimpath
        ldflags:
          - -s
          - -w
  tagPolicy:
    inputDigest: {}
  platforms:
    - linux/amd64
    - linux/arm64/v8
manifests:
  rawYaml:
    - kubernetes.yaml
deploy:
  kubectl:
    defaultNamespace: reqlog
  kubeContext: user@asami
