kind: Namespace
metadata:
  name: softserve
apiVersion: v1
---
kind: Deployment
metadata:
  name: softserve
  namespace: kube-system
  labels:
    app.kubernetes.io/name: softserve
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: softserve
  template:
    metadata:
      labels:
        app.kubernetes.io/name: softserve
    spec:
      containers:
        - image: ghcr.io/charmbracelet/soft-serve:v0.7.4
          name: softserve
          ports:
            - containerPort: 9418
              name: git
            - containerPort: 23231
              hostPort: 23231
              name: git-ssh
            - containerPort: 23232
              name: git-http
            - containerPort: 23233
              name: stats
          volumeMounts:
            - mountPath: /soft-serve
              name: data
      enableServiceLinks: false
      volumes:
        - hostPath:
            path: /opt/volumes/softserve
          name: data
  strategy:
    type: Recreate
  revisionHistoryLimit: 1
apiVersion: apps/v1
