kind: ConfigMap
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
    processors:
      transform:
        error_mode: ignore
        trace_statements:
          - context: resource
            statements:
              - set(attributes["k8s.cluster.name"], "justia")
              - set(attributes["deployment.environment"], "production")
        metric_statements:
          - context: resource
            statements:
              - set(attributes["k8s.cluster.name"], "justia")
              - set(attributes["deployment.environment"], "production")
        log_statements:
          - context: resource
            statements:
              - set(attributes["k8s.cluster.name"], "justia")
              - set(attributes["deployment.environment"], "production")
    exporters:
      googlecloud:
        project: com-seankhliao
      nop: {}
    extensions:
      health_check: {}
      pprof: {}
      zpages: {}
    service:
      extensions:
        - health_check
        - pprof
        - zpages
      pipelines:
        logs:
          receivers:
            - otlp
          processors:
            - transform
          exporters:
            - nop
        metrics:
          receivers:
            - otlp
          processors:
            - transform
          exporters:
            - nop
        traces:
          receivers:
            - otlp
          processors:
            - transform
          exporters:
            - googlecloud
metadata:
  name: otelcol
  namespace: opentelemetry
  labels:
    app.kubernetes.io/part-of: opentelemetry
    app.kubernetes.io/name: opentelemetry
  annotations:
    config.kubernetes.io/origin: "\tmono/deploy/opentelemetry/*.cue"
apiVersion: v1
---
kind: ConfigMap
data:
  creds.json: '{"universe_domain":"googleapis.com","type":"external_account","audience":"//iam.googleapis.com/projects/330311169810/locations/global/workloadIdentityPools/kubernetes/providers/justia-asami","subject_token_type":"urn:ietf:params:oauth:token-type:jwt","token_url":"https://sts.googleapis.com/v1/token","credential_source":{"file":"/var/run/service-account/token","format":{"type":"text"}},"token_info_url":"https://sts.googleapis.com/v1/introspect"}'
metadata:
  name: gcp
  namespace: opentelemetry
  labels:
    app.kubernetes.io/part-of: opentelemetry
    app.kubernetes.io/name: opentelemetry
  annotations:
    config.kubernetes.io/origin: "\tmono/deploy/opentelemetry/*.cue"
apiVersion: v1
---
kind: Namespace
metadata:
  name: opentelemetry
  labels:
    app.kubernetes.io/part-of: opentelemetry
    app.kubernetes.io/name: opentelemetry
  annotations:
    config.kubernetes.io/origin: "\tmono/deploy/opentelemetry/*.cue"
apiVersion: v1
---
spec:
  type: ClusterIP
  ports:
    - name: otlp-grpc
      port: 4317
      protocol: TCP
      appProtocol: grpc
      targetPort: otlp-grpc
    - name: otlp-http
      port: 4318
      protocol: TCP
      appProtocol: http
      targetPort: otlp-http
  selector:
    app.kubernetes.io/name: otelcol
kind: Service
apiVersion: v1
metadata:
  name: otelcol
  namespace: opentelemetry
  annotations:
    config.kubernetes.io/origin: "\tmono/deploy/opentelemetry/*.cue"
  labels:
    app.kubernetes.io/part-of: opentelemetry
    app.kubernetes.io/name: opentelemetry
---
kind: Deployment
metadata:
  name: otelcol
  namespace: opentelemetry
  labels:
    app.kubernetes.io/part-of: opentelemetry
    app.kubernetes.io/name: otelcol
  annotations:
    config.kubernetes.io/origin: "\tmono/deploy/opentelemetry/*.cue"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: otelcol
  template:
    metadata:
      labels:
        app.kubernetes.io/name: otelcol
    spec:
      automountServiceAccountToken: true
      containers:
        - name: otelcol
          image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.104.0
          args:
            - --config=file:/etc/otelcol/config.yaml
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/run/service-account/creds.json
          ports:
            - name: otlp-grpc
              containerPort: 4317
            - name: otlp-http
              containerPort: 4318
            - name: healthcheck
              containerPort: 13133
            - name: zpages
              containerPort: 55679
          volumeMounts:
            - name: token
              mountPath: /var/run/service-account
              readOnly: true
            - name: config
              mountPath: /etc/otelcol
      volumes:
        - name: token
          projected:
            sources:
              - serviceAccountToken:
                  audience: https://iam.googleapis.com/projects/330311169810/locations/global/workloadIdentityPools/kubernetes/providers/justia-asami
                  expirationSeconds: 3600
                  path: token
              - configMap:
                  name: gcp
        - name: config
          configMap:
            name: otelcol
      enableServiceLinks: false
  revisionHistoryLimit: 1
apiVersion: apps/v1
