apiVersion: v1
kind: Namespace
metadata:
  name: moo
---
apiVersion: v1
kind: Service
metadata:
  name: moo
  namespace: moo
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: debug
      port: 8081
      targetPort: debug
  selector:
    app.kubernetes.io/name: moo
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moo
  namespace: moo
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: moo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: moo
    spec:
      containers:
        - env:
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/name']
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: k8s.pod.uid=$(POD_UID),k8s.container.name=moo
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otelcol.opentelemetry.svc:4317
          image: ko://go.seankhliao.com/mono/cmd/moo
          name: moo
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8081
              name: debug
      enableServiceLinks: false
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: moo
  namespace: moo
spec:
  hostnames:
    - reqlog.liao.dev
  parentRefs:
    - name: http-gateway
      namespace: envoy-gateway-system
  rules:
    - backendRefs:
        - name: moo
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
