apiVersion: v1
kind: Namespace
metadata:
  name: ghdefaults
---
apiVersion: v1
kind: Service
metadata:
  name: ghdefaults
  namespace: ghdefaults
spec:
  ports:
    - appProtocol: HTTP
      name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: ghdefaults
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghdefaults
  namespace: ghdefaults
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ghdefaults
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ghdefaults
    spec:
      containers:
        - args:
            - -gh.app.id=file:///var/run/secrets/github/app-id
            - -gh.app.private-key=file:///var/run/secrets/github/private-key
            - -gh.webhook.secret=file:///var/run/secrets/github/webhook-secret
          env:
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/name']
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: k8s.pod.uid=$(POD_UID),k8s.cluster.name=ihwa,k8s.container.name=earbug
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://ingest.otelcol.svc:4317
          image: ghcr.io/seankhliao/ghdefaults
          livenessProbe:
            httpGet:
              path: /-/ready
              port: http
          name: ghdefaults
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          startupProbe:
            httpGet:
              path: /-/ready
              port: http
          volumeMounts:
            - mountPath: /var/run/secrets/github
              name: secrets
      enableServiceLinks: false
      volumes:
        - name: secrets
          secret:
            secretName: ghdefaults
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  annotations:
    config.kubernetes.io/origin: |
      path: httproute.k8s.yaml
  labels:
    app.kubernetes.io/managed-by: kustomize-v5.0.3
  name: ghdefaults
spec:
  hostnames:
    - ghdefaults.liao.dev
  parentRefs:
    - name: default
      namespace: envoy-gateway-system
  rules:
    - backendRefs:
        - name: ghdefaults
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
