apiVersion: v1
kind: Namespace
metadata:
  name: ihwa-liao-dev
---
apiVersion: v1
kind: Service
metadata:
  name: ihwa-liao-dev
  namespace: ihwa-liao-dev
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: ihwa-liao-dev
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ihwa-liao-dev
  namespace: ihwa-liao-dev
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ihwa-liao-dev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ihwa-liao-dev
    spec:
      containers:
        - env:
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/name']
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: k8s.pod.uid=$(POD_UID),k8s.cluster.name=ihwa,k8s.container.name=ihwa-liao-dev
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://ingest.otelcol.svc:4317
          image: ko://go.seankhliao.com/mono/cmd/ihwa-liao-dev
          name: ihwa-liao-dev
          ports:
            - containerPort: 8080
              name: http
      enableServiceLinks: false
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: ihwa-liao-dev
  namespace: ihwa-liao-dev
spec:
  hostnames:
    - ihwa.liao.dev
  parentRefs:
    - name: default
      namespace: envoy-gateway-system
  rules:
    - backendRefs:
        - name: ihwa-liao-dev
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: ihwa-liao-dev
  namespace: ihwa-liao-dev
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ihwa-liao-dev
