apiVersion: v1
kind: Namespace
metadata:
  name: reqlog
---
apiVersion: v1
kind: Service
metadata:
  name: reqlog
  namespace: reqlog
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: reqlog
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reqlog
  namespace: reqlog
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: reqlog
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reqlog
    spec:
      containers:
        - env:
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/name']
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: k8s.pod.uid=$(POD_UID),k8s.container.name=reqlog
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otelcol.opentelemetry.svc:4317
          image: ko://go.seankhliao.com/mono/cmd/reqlog
          name: reqlog
          ports:
            - containerPort: 8080
              name: http
      enableServiceLinks: false
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: reqlog
  namespace: reqlog
spec:
  hostnames:
    - reqlog.liao.dev
  parentRefs:
    - name: http-gateway
      namespace: envoy-gateway-system
  rules:
    - backendRefs:
        - name: reqlog
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
